Bullitin_Board/Buulitin_board/Buulitin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from Buulitin_board import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('users/', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bullitin_Board/Buulitin_board/board/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<int:cat_id>', PostCategory.as_view(), name='category'),
    path('post/<int:post_id>/', ShowPost.as_view(), name='post'),
    path('edit/<int:pk>/', EditPost.as_view(), name='edit'),
    path('add_post/', Add_Post.as_view(), name='add_post'),

]

Bullitin_Board/Buulitin_board/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signin/', SigninUser.as_view(), name='signin'),
    path('profile/', ProfileUserView.as_view(), name='profile'),

    #ajax
    #path('reply_status/<int:pk>/<slug:type>', reply_status(), name='reply_status'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ),
         name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]


Bullitin_Board/Buulitin_board/users/models.py
from django.db import models

# Create your models here.


# class ReplyFilter(models.Manager):
#     reply = models.ForeignKey(Reply, on_delete=models.CASCADE, blank=True, related_name='reply_filter')
#
#     def get_queryset(self):
#         #return super().get_queryset().filter(status=False)
#         return super().get_queryset().all()

Bullitin_Board/Buulitin_board/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин или E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class SigninUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput)
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', widget=forms.EmailInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',

        }

    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password1'] != cd['password2']:
    #         raise forms.ValidationError('Пароли не совпадают')
    #     return cd['password1']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой Email уже существует')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин', disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='E-mail', disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


Bullitin_Board/Buulitin_board/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render
from django_filters import FilterSet

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from .forms import *
from board.models import *


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class SigninUser(CreateView):
    form_class = SigninUserForm
    template_name = 'users/signin.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    form_class = ProfileUserForm
    model = get_user_model()
    template_name = 'users/profile.html'
    context_object_name = 'posts'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_posts = Post.objects.filter(author=self.request.user)
        context['user_posts'] = user_posts

    # def get_queryset(self):
    #     return Post.objects.filter(author=self.request.user)


class PostFilter(FilterSet):

    class Meta:
        model = Reply
        fields = ['post']

    def __init__(self, *args, **kwargs):
        super(PostFilter, self).__init__(*args, **kwargs)
        self.filters['post'].queryset = Post.objects.filter(author_id=kwargs['request'])


class ProfileUserView(LoginRequiredMixin, ListView):
    model = Reply
    template_name = 'users/profile2.html'
    context_object_name = 'replies'

    def get_queryset(self):
        queryset = Reply.objects.filter(post__author_id=self.request.user.id)
        self.filterset = PostFilter(self.request.GET, queryset, request=self.request.user.id)
        if self.request.GET:
            return self.filterset.qs
        return Reply.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


# def reply_status(request, pk, type):
#         return HttpResponse('Тест')


    # def user_replies(self, request):
    #     user = request.user
    #     replies = Reply.objects.id(pk=user.id)
    #     return replies

Bullitin_Board/Buulitin_board/templates/users/login.html
{% extends 'index.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p><button type="submit">Войти</button></p>
  <p><button type="submit"><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></button></p>
</form>

{% endblock %}

Bullitin_Board/Buulitin_board/templates/users/password_reset_complete.html
{% extends 'index.html' %}

{% block content %}
<h1>Пароль изменен!</h1>

<p>
  Вы успешно изменили пароль своего аккаунта.
  Используйте его для <a href="{% url 'users:login' %}">входа в систему</a>
</p>


{% endblock %}


Bullitin_Board/Buulitin_board/templates/users/password_reset_confirm.html
{% extends 'index.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="text" value="next" />

   {{form.as_p}}

  <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}


Bullitin_Board/Buulitin_board/templates/users/password_reset_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block content %}

<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

Bullitin_Board/Buulitin_board/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

Bullitin_Board/Buulitin_board/templates/users/password_reset_form.html
{% extends 'index.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="text" value="next" />

   {{form.as_p}}

  <p><button type="submit">Сбросить пароль</button></p>
</form>

{% endblock %}


Bullitin_Board/Buulitin_board/templates/users/profile.html
{% extends 'index.html' %}

{% block content %}
<h1>Профиль пользователя - {{ user.username }}</h1>
<hr>

<h3>Изменить личные данные</h3>
<form method="post">
  {% csrf_token %}
  <input type="hidden" name="text" value="next" />

   {{form.as_p}}

  <p><button type="submit">Сохранить</button></p>
</form>
<hr>
<h2>Ваши объявления</h2>
    {% if user_posts %}
        {% for up in user_posts %}
            {{ up.title }}
            {{ up.content }}
            {{ up.data }}
        {% endfor %}
    {% else %}
        <b>Вы еще не опубликовали ни одного поста</b>
    {% endif %}
<hr>
<h2>Ваши отклики</h2>
    {% if post.reply_post.all %}
        {% for p in post.reply_post.all %}
            <ul><p><b><i>{{ p.author }}</i></b></p></ul>
            <small><i>{{ p.datetime }}</i></small>
            <small><b>{{ p.reply_status }}</b></small>
            <p>{{ p.text }}</p>
            <small>
                <a href="#"> Опубликовать </a>
            </small>
            <hr>
        {% endfor %}
    {% else %}
        <h6>Никто еще не оставил вам откликов</h6>
    {% endif %}



{% endblock %}



{% if post.reply_post.all %}
        {% for p in post.reply_post.all %}
        <ul><p><b><i>{{ p.author }}</i></b></p></ul>
        <small><i>{{ p.datetime }}</i></small>
        <small><b>{{ p.reply_status }}</b></small>
        <p>{{ p.text }}</p>
        <hr>
        {% endfor %}
    {% else %}
        <h6>Никто еще не оставил откликов</h6>
    {% endif %}

Bullitin_Board/Buulitin_board/templates/users/profile2.html
{% extends 'index.html' %}

{% block content %}
<h1>Профиль пользователя - {{ user.username }}</h1>
<hr>

<hr>
<h2>Ваши объявления</h2>
  <form action="" method="get">
      {{ filterset.form }}
      <input type="submit" value="Найти">
  </form>
<hr>
<h2>Ваши отклики</h2>
    {% if replies %}
        {% for reply in replies %}
            <ul><p><b><i>{{ reply.author }}</i></b></p></ul>
            <small><i>{{ reply.datetime }}</i></small>
            <small><b>{{ reply.reply_status }}</b></small>
            <p>{{ reply.text }}</p>
            <small>
                <a href="#"> Опубликовать </a>
            </small>
            <hr>
        {% endfor %}
    {% else %}
        <h6>Никто еще не оставил вам откликов</h6>
    {% endif %}



{% endblock %}



{% if post.reply_post.all %}
        {% for p in post.reply_post.all %}
        <ul><p><b><i>{{ p.author }}</i></b></p></ul>
        <small><i>{{ p.datetime }}</i></small>
        <small><b>{{ p.reply_status }}</b></small>
        <p>{{ p.text }}</p>
        <hr>
        {% endfor %}
    {% else %}
        <h6>Никто еще не оставил откликов</h6>
    {% endif %}

Bullitin_Board/Buulitin_board/templates/users/signin.html
{% extends 'index.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="text" value="next" />

   {{form.as_p}}

  <p><button type="submit">Зарегистрироваться</button></p>
</form>

{% endblock %}


Bullitin_Board/Buulitin_board/templates/users/signin_ok.html
{% extends 'index.html' %}

{% block content %}
<h1>Добро пожаловать</h1>

<p>
  Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться.
  Вы можете сделать это <a href="{% url 'users:login' %}"><b>здесь</b></a>
</p>

{% endblock %}
