NewsPapper/NewsPapper/urls.py
from django.contrib import admin
from django.urls import path, include
from news.tasks.tasks import MyTask


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    path('tasks/', MyTask.as_view()),

]


NewsPapper/news/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', NewsHome.as_view(), name='home'),
    path('news/', NewsList.as_view(), name='news'),
    path('news/create/', AddNews.as_view(), name='add_news'),
    path('news/<int:pk>/edit/', NewsEdit.as_view(), name='edit_news'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='delete_news'),
    path('news/search', Search.as_view(), name='search'),
    path('post/<int:post_id>/', ShowPost.as_view(), name='post'),
    path('category/<int:cat_id>', NewsCategory.as_view(), name='category'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('signin/', SignIn.as_view(), name='signin'),
    path('news/create/upgrade/', upgrade_authors, name='upgrade'),
    path('category/<int:cat_id>/subscribe', subscribe, name='subscribe'),
    path('category/<int:cat_id>/unsubscribe', unsubscribe, name='unsubscribe'),

    #path('profile/', UserProfile.as_view(), name='profile')


]

NewsPapper/news/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse


type = [
    ('ARTICLE', 'Статья'),
    ('NEWS', 'Новость')
]

oauth_user = Group.objects.get(name='authors')


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Содержание')
    date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT,  verbose_name='Категория')
    auth = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор', blank=True, default='admin')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_id': self.pk})

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'News'

    def preview(self):
        preview = f'{self.description[:50]}'
        return preview

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name_plural = 'Категории'


class NewsCategory(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Author(models.Model):
    name = models.CharField(max_length=50),
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('authors', kwargs={'user_auth_id': self.pk})


class Comment(models.Model):
    news_com = models.ForeignKey(News, on_delete=models.CASCADE)
    news_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    com_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPapper/news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from allauth.account.forms import SignupForm

from .models import *

class AddNewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'description', 'cat', 'auth']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 255:
            raise ValidationError('Длина превышает 255 символов')
        else:
            return title

    def clean_description(self):
        cleaned_data = super().clean()
        description = cleaned_data.get('description')
        if description is not None and len(description) < 20:
            raise ValidationError({'description': 'Описание не может быть менее 20 символов'})
        return cleaned_data


class SignInForm(UserCreationForm):

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    # class Meta:
    #     model = User
    #     fields = ('username', 'email', 'password1', 'password2')
    #     widgets = {
    #             'username': forms.TextInput(attrs={'class': 'form-input'}),
    #             'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
    #             'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
    #     }


''' Если нужно, чтобы заработал класс Мета нужно заменить модель User из .models на django.contrib.auth.models,
раскомментировать класс'''


# class UserSignUpForm(SignupForm):
#     email = forms.EmailField(label="Email")
#     first_name = forms.CharField(label="Имя")
#     last_name = forms.CharField(label="Фамилия")
#
#     class Meta:
#         model = User
#         fields = ("username",
#                   "first_name",
#                   "last_name",
#                   "email",
#                   "password1",
#                   "password2",)
#
#     def save(self, request):
#         user = super(UserSignUpForm, self).save(request)
#         basic_group = Group.objects.get(name='common')
#         basic_group.user_set.add(user)
#         return user

class CommonSignupForm(SignupForm):

    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user


class LogInForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

NewsPapper/news/views.py
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout

from django.conf import settings
from datetime import datetime

from .models import *
from .forms import *
from .utils import *
from .filters import NewsFilter


DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL


class NewsHome(DataMixin, ListView):
    model = News
    template_name = 'news/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return dict(list(context.items()) + list(c_def.items()))


class NewsList(DataMixin, ListView):
    paginate_by = 10
    model = News
    template_name = 'news/NewsList.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Список новостей')
        return dict(list(context.items()) + list(c_def.items()))


class ShowPost(DataMixin, DetailView):
    model = News
    template_name = 'news/post.html'
    pk_url_kwarg = 'post_id'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['post'])
        return dict(list(context.items()) + list(c_def.items()))


class NewsCategory(ListView, DataMixin):
    model = News
    template_name = 'news/category_list2.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):

        return News.objects.filter(cat__id=self.kwargs['cat_id']).select_related('cat')

    def get_context_data(self, *, object_list=None, **kwargs):
        # c = Category.objects.get(id=self.kwargs['cat_id'])
        # c_def = self.get_user_context(
        #     title='Категория - ' + str(c.name),
        #     cat_selected=c.pk
        # )
        # context = super().get_context_data(**kwargs)
        # context['is_not_subscriber'] = self.request.user not in \
        #                                Category.objects.get(id=self.kwargs['cat_id']).subscribers.all()
        #
        # return dict(list(context.items()) + list(c_def.items()))

        c = Category.objects.get(id=self.kwargs['cat_id'])
        c_def = self.get_user_context(
            title='Категория - ' + str(c.name),
            cat_selected=c.pk
        )
        context = super().get_context_data(**kwargs)
        user = self.request.user
        subscribed = c.subscribers.filter(email=user.email)
        if not subscribed:
            context['c'] = c

        return dict(list(context.items()) + list(c_def.items()))


@login_required
def subscribe(requests, cat_id):
    message = 'Вы подписаны на рассылку категории'
    user = requests.user
    category = Category.objects.get(id=cat_id)
    if not category.subscribers.filter(id=user.id).exists():
        category.subscribers.add(user)
        email = user.email

        html = render_to_string(
            'news/subscribe.html',
            {
                'categories': category,
                'user': user
            }
        )
        msg = EmailMultiAlternatives(
            subject=f'Категория {category} - подписка оформлена',
            body='',
            from_email=DEFAULT_FROM_EMAIL,
            to=[email, ],
        )
        msg.attach_alternative(html, 'text/html')

        try:
            msg.send()
        except Exception as e:
            print(e)
        return redirect('/')
#    return redirect(requests, 'news/subscribe.html', {'category': category, 'message': message}), \
#           redirect('news/category_list2.html')
#    return redirect(requests.META.get('HTTP_REFERER'))


@login_required
def unsubscribe(requests, cat_id):
    user = requests.user
    category = Category.objects.get(id=cat_id)

    if category.subscribers.filter(id=user.id).exists():
        category.subscribers.remove(user)
    return redirect('/')



class AddNews(LoginRequiredMixin, PermissionRequiredMixin, DataMixin, CreateView):
    permission_required = ('news.add_news')
    form_class = AddNewsForm
    template_name = 'news/add_news.html'
    success_url = reverse_lazy('home')
    login_url = reverse_lazy('home')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        c_def = self.get_user_context(title='Добавить новость')
        return dict(list(context.items()) + list(c_def.items()))


@login_required
def upgrade_authors(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        Author.objects.create(user=user)
        authors_group.user_set.add(user)

    return redirect('/')


class NewsEdit(UpdateView, DataMixin):
    form_class = AddNewsForm
    model = News
    template_name = 'news/add_news.html'


class NewsDelete(DeleteView, DataMixin):
    model = News
    template_name = 'news/add_news.html'
    success_url = reverse_lazy('news')


class Search(DataMixin, ListView):
    model = News
    template_name = 'news/search.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_filter(self):
        return NewsFilter(self.request.GET, queryset=super().get_queryset())


    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *args, **kwargs):
        context = {
            **super().get_context_data(*args, **kwargs),
            'filter': self.get_filter()
        }
        c_def = self.get_user_context(title='Поиск новостей')
        return dict(list(context.items()) + list(c_def.items()))


class Login(DataMixin, LoginView):
    form_class = LogInForm
    template_name = 'news/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        return dict(list(context.items()) + list(c_def.items()))


def logout_user(requests):
    logout(requests)
    return redirect('login')


class SignIn(DataMixin, CreateView):
    form_class = SignInForm
    template_name = 'news/signin.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


def PageNotFound(request, exeption):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')




NewsPapper/news/templates/news/NewsList.html
{% extends 'news/default.html' %}

{% block content %}
<h1>{{title}}</h1>



<ul class="news_list">
    {% for p in posts %}
    <li>
        <p class="first">Категория: {{p.cat}}</p>
        <h2>{{p.title}}</h2>
        <p><small><i>{{p.date}}</i></small></p>
        <p>{{p.description|truncatechars:50}}</p>
        <p><small><b>Автор: {{p.auth}}</b></small></p>
        <p class="link-read-post"><a href="{{p.get_absolute_url}}">Читать новость</a></p>
        <hr>
    </li>
    {% endfor %}
</ul>
{% endblock %}


NewsPapper/news/templates/news/add_news.html
{% extends 'news/default.html' %}

{% block content %}

<h1>{{title}}</h1>

<form action="{% url 'add_news' %}" method="post">
    {% csrf_token %}

 <!--   {{ form.as_p }} -->

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% if is_not_authors %}
        <h3>Вы не можете добавлять новости, так как не являетесь автором</h3>
        <button><a href="upgrade"> Стать автором </a></button>
    {% else %}
        {% for f in form %}
            <p>
                <label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label> {{ f }}
            </p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit">Добавить новость</button>
     {% endif %}


</form>

{% endblock %}

NewsPapper/news/templates/news/category_list1.html
{% extends 'news/default.html' %}

{% block title %}
<h1>{{title}}</h1>
{% endblock title %}

{% for c in cats %}

	{% if c.pk == cat_selected %}
		<li class="selected">{{c.name}}</li>
	{% else %}
		<li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
	{% endif %}
{% endfor %}

{% block content %}
	{% if is_not_subscriber %}
		<p class="text-center"><button><a href="{% url 'subscribe' category.id %}">Подписаться</a></button></p>
	{% endif %}


<ul class="news_list">
    {% for с in category_news_list %}
    <li>
        <p class="first">Категория:
            {% for category in с.category.all %}
                <a href="{% url 'category_list' category.id %}"> {{category}}</a></p>
            {% endfor %}
        <p><small>автор: {{с.auth}}</small></p>
        <h2>{{с.title}}</h2>
        <p>{{с.date}}</p>
        <p>{{с.description|truncatechars:20}}</p>
        <p class="read_post"><a href="{{с.get_absolute_url}}">Читать новость</a></p>
        <hr>
    </li>
    {% endfor %}
</ul>
{% endblock %}

NewsPapper/news/templates/news/category_list2.html
{% extends 'news/default.html' %}

{% block content %}
<h1>{{title}}</h1>






<ul class="news_list">
    {% for p in posts %}
    <li>
        {% if c %}
            <p class="first">Категория: {{p.cat}} -
            <em><a href="{% url 'subscribe' c.id %}" > подписаться на категорию</a></em>
            </p>
        {% else %}
            <p class="first">
                <em>Категория: {{p.cat}}</em> - вы подписаны!
                <em><a href="{% url 'unsubscribe' c.id %}"> Отписаться</a></em>
            </p>
        {% endif %}
        <small>автор: {{p.auth}}</small>
        <h2>{{p.title}}</h2>
        <p>{{p.date}}</p>
        <p>{{p.description|truncatechars:20}}</p>
        <p class="link-read-post"><a href="{{p.get_absolute_url}}">Читать новость</a></p>
        <hr>
    </li>
    {% endfor %}
</ul>
{% endblock %}

NewsPapper/news/templates/news/deafeult-2.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'news/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<table class="table-page" border="0" cellpadding="0" cellspacing="0">
{% block mainmenu %}
		<ul>
	<li class="mainmenu"><a href="{% url 'home' %}"></a></li>
	{% for m in menu %}
		{% if not forloop.last %}
			<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
		{% else %}
			<li class="last"><a href="{% url m.url_name %}">{{m.title}}</a></li>
		{% endif%}
	{% endfor %}
		</ul>
{% endblock mainmenu %}

<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li>
{% endif %}


{% for c in cats %}
	{% if c.pk == cat_selected %}
		<li class="selected">{{ c.name }}</li>
	{% else %}
		<li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
	{% endif %}
{% endfor %}

	</ul>
<!-- Конец Sidebar'а -->

</td></tr></table>

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>

</body>
</html>

NewsPapper/news/templates/news/default.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'news/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in menu %}
		<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
				{% if request.user.is_authenticated %}
					<li class="last"> {{user.username}} | <a href="{% url 'account_logout' %}"> Выйти</a> </li>
				{% else %}
					<li class="last"><a href="{% url 'account_signup' %}">Регистрация</a> | <a href="{% url 'account_login' %}"> Войти </a> </li>
				{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
{% else %}
		<li><a href="{% url 'news' %}">Все категории</a></li>
{% endif %}

{% for c in cats %}
	{% if c.pk == cat_selected %}
		<li class="selected">{{ c.name }}</li>
	{% else %}
		<li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
	{% endif %}
{% endfor %}



	</ul>
	</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">

{% block content %}

{% endblock %}


<nav class="list-pages">
	<ul>
{% if page_obj.has_previous %}
<li class="page-num">
	<a href="?page={{ page_obj.first_page_number }}">Первая страница</a>
</li>
{% endif %}
		{% for p in paginator.page_range %}
		{% if page_obj.number == p %}
		<li class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obj.number|add:-1 and p <= page_obj.number|add:1 %}
		<li class="page-num">
			<a href="?page={{ p }}">{{ p }}</a>
		</li>
		{% endif %}
		{% endfor %}
{% if page_obj.has_next %}
<li class="page-num">
	<a href="?page={{ page_obj.last_page_number }}">Последняя страница</a>
</li>
{% endif %}
	</ul>
</nav>

	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, разрешено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

NewsPapper/news/templates/news/index.html
{% extends 'news/default.html' %}



{% block content %}
<h1>{{title}}</h1>
<p>Содержимое главной страницы
{% endblock %}

NewsPapper/news/templates/news/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Post</title>
</head>
<body>
  <h1>Новый пост в категории: {{ category.name }}</h1>
  <a href="{{ p.get_absolute_url }}">
     <h2>{{p.title}}</h2>
  </a>
</body>
</html>

NewsPapper/news/templates/news/search.html
{% extends 'news/default.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="get">
       {{ filter.form.as_p }}
       <input type="submit" value="Найти" />
</form>
       {% for obj in posts %}
              {{ obj.date }}---{{ obj.title }}---{{ obj.description|truncatechars:20 }}<br />
       {% endfor %}

{% endblock %}

NewsPapper/news/templates/news/show_cat.html
{% extends 'news/default.html' %}

{% for c in cats %}

	{% if c.pk == cat_selected %}
		<li class="selected">{{c.name}}</li>
	{% else %}
		<li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
	{% endif %}
{% endfor %}


NewsPapper/news/templates/news/signin.html
{% extends 'news/default.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }}:  </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}


    <button type="submit">Регистрация</button>
</form>

{% endblock %}

NewsPapper/news/templates/news/signup.html
{% extends "default.html" %}

{% block content %}
<h2> Регистрация </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}

NewsPapper/news/templates/news/unsubscribe.html
{% extends 'news/default.html' %}

{% block content %}
    <h1>{{ message }}</h1>
{% endblock %}

NewsPapper/news/templates/news/update_user.html
{% extends 'news/default.html' %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href="account/logout/">Выйти</a> </button>
{% endblock %}