Bullitin_Board/Buulitin_board/Buulitin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from Buulitin_board import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('users/', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bullitin_Board/Buulitin_board/board/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<int:cat_id>', PostCategory.as_view(), name='category'),
    path('post/<int:post_id>/', ShowPost.as_view(), name='post'),
    path('edit/<int:pk>/', EditPost.as_view(), name='edit'),
    path('add_post/', Add_Post.as_view(), name='add_post'),

]

Bullitin_Board/Buulitin_board/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signin/', SigninUser.as_view(), name='signin'),
    path('profile/', ProfileUserView.as_view(), name='profile'),

    #ajax
    #path('reply_status/<int:pk>/<slug:type>', reply_status(), name='reply_status'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ),
         name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]


Bullitin_Board/Buulitin_board/templates/base.html
{% load static %}

{% include 'index.html' %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    <link type="text/css" href="{% static 'board/css/styles.css' %}" rel="stylesheet" />

</head>
<body>

{% block mainmenu %}
    {% for pm in profile_menu %}
        {{ pm.title }}
    {% endfor %}
{% endblock mainmenu%}

{% block content %}
{% endblock content %}
</body>
</html>


Bullitin_Board/Buulitin_board/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Доска объявлений</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link type="text/css" href="{% static 'board/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">

        {% block sidebar %}
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Категории объявлений</div>

                <div class="list-group list-group-flush">
                {% for c in categories %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'category' c.id %}">{{ c.name }}</a>
                {% endfor %}

                </div>
            </div>
        {% endblock sidebar %}

            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <a href="{% url 'home' %}"><button class="btn btn-primary" id="sidebarToggle">Доска объявлений</button></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                {% for pm in profile_menu %}
                                <li class="nav-item active"><a class="nav-link" href="{% url pm.url_name %}">{{ pm.title }}</a></li>
                                {% endfor %}
                                {% if user.is_authenticated %}
                                    <li class="nav-item active"><a class="nav-link" href="{% url 'add_post' %}">Добавить объявление | </a></li>
                                    <li class="nav-item active"><a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }} | </a></li>
                                    <li class="nav-item active"><a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></li>
                                {% else %}
                                <li class="nav-item active"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></li> |
                                <li class="nav-item active"><a class="nav-link" href="{% url 'users:signin' %}">Регистрация</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                {% block content %}
                <div class="container-fluid">
                    <h1 class="mt-4">{{ title }}</h1>
                </div>
                {% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Bullitin_Board/Buulitin_board/templates/tests.html
 <!-- Навигационное меню -->

    <ul>
        {% for m in menu %}
         <li>
            <a href="{% url m.url_name %}">{{ m.title }}</a>
         </li>
        {% endfor %}
    </ul>


 <!-- Сайдбар с дропдауном -->

    {% if m.title == 'Категории объявлений'%}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ m.title }}</a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#!">Action</a>
                    <a class="dropdown-item" href="#!">Another action</a>
                        <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#!">Something else here</a>
                </div>
        </li>
    {% endif %}